config/routes.rb
Rails.application.routes.draw do

  resources :suggestions

  root 'suggestions#index'

end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController

  def index
    @suggestions = Suggestion.all
  end

  def show
    @suggestion = Suggestion.find(params[:id])
  end

  def new
    @suggestion = Suggestion.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Iiname2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<%= yield %>
<br>
<table>
  <caption>すきなほうを選んでください</caption>
  <tr><td><%= image_tag('udon.png', :size => "450x391", :alt => "うどん") %></td>
  <td><%= image_tag('soba.png', :size => "450x393", :alt => "そば") %></td></tr>
</body>
</html>

app/views/suggestions/index.html.erb
<h1>iiname</h1>

<ul>
<% @suggestions.each do |suggestion| %>
<li>
  <%= link_to suggestion.title, suggestion_path(suggestion) %>
  <%= link_to 'Edit', edit_suggestion_path(suggestion) %>
</li>
<% end %>
</ul>
<%= link_to 'home', suggestions_path %> | <%= link_to 'New', new_suggestion_path %>
<button class="showAnswer">確認</button>

app/views/suggestions/show.html.erb
<h1><%= @suggestion.title %></h1>

<%= @suggestion.content %>

<%= link_to 'home', suggestion_path %>